// lib/data.ts - Central data store (can be replaced with a real DB later)

export interface Destination {
  id: string
  name: string
  slug: string
  category: 'alam' | 'kuliner' | 'budaya' | 'pantai' | 'desa' | 'umkm'
  location: string
  distance: string
  crowdLevel: 'low' | 'medium' | 'high'
  rating: number
  reviewCount: number
  image: string
  tags: string[]
  description: string
  tips: string
  coordinates: { lat: number; lng: number }
  matchScore?: number
  ticketPrice?: { min: number; max: number }
  foodPrice?: { min: number; max: number }
  openHours?: string
}

export interface Post {
  id: string
  author: string
  avatar: string
  badge: string
  time: string
  category: string
  title: string
  body: string
  image?: string
  votes: number
  comments: number
  tags: string[]
}

export interface CrowdReport {
  name: string
  level: 'rendah' | 'sedang' | 'padat' | 'lancar'
  color: string
  trend: 'up' | 'down' | 'stable'
}

export const destinations: Destination[] = [
  // ═══════════════════════════════════════════
  // ALAM (10 destinations)
  // ═══════════════════════════════════════════
  {
    id: '1',
    name: 'Sumber Sirah',
    slug: 'sumber-sirah',
    category: 'alam',
    location: 'Kepanjen, Malang',
    distance: '28 km dari Kota',
    crowdLevel: 'low',
    rating: 4.8,
    reviewCount: 234,
    image: 'https://senyumworldhotel.com/wp-content/uploads/2023/07/Sumber-Sira.jpg',
    tags: ['#AirJernih', '#ProdukLokal', '#Hidden'],
    description: 'Wisata air jernih dengan ekosistem laut tawar yang memukau. Airnya berwarna biru kehijauan dan sangat jernih.',
    tips: 'Datang sebelum jam 8 pagi untuk menghindari keramaian.',
    coordinates: { lat: -8.1845, lng: 112.5595 },
    matchScore: 98,
    ticketPrice: { min: 10000, max: 15000 },
    openHours: '06:00 - 17:00',
  },
  {
    id: '2',
    name: 'Coban Pelangi',
    slug: 'coban-pelangi',
    category: 'alam',
    location: 'Poncokusumo, Malang',
    distance: '35 km dari Kota',
    crowdLevel: 'medium',
    rating: 4.7,
    reviewCount: 891,
    image: 'https://gubugklakah.com/wp-content/uploads/2025/07/IMG_6775-768x1024.jpg',
    tags: ['#Pelangi', '#Trekking', '#Fotografi'],
    description: 'Air terjun pelangi yang megah di kaki Semeru. Terkenal karena fenomena pelangi yang muncul setiap hari.',
    tips: 'Waktu terbaik antara 10-12 siang saat matahari tinggi untuk melihat pelangi.',
    coordinates: { lat: -8.0632, lng: 112.9075 },
    matchScore: 92,
    ticketPrice: { min: 15000, max: 25000 },
    openHours: '07:00 - 16:00',
  },
  {
    id: '7',
    name: 'Bukit Cinta Bromo',
    slug: 'bukit-cinta-bromo',
    category: 'alam',
    location: 'Tosari, Pasuruan',
    distance: '75 km dari Kota',
    crowdLevel: 'medium',
    rating: 4.9,
    reviewCount: 1543,
    image: 'https://travelspromo.com/wp-content/uploads/2022/02/jembatan-di-bukit-cinta-ambarawa-1.jpg',
    tags: ['#Sunrise', '#Bromo', '#Fotografi'],
    description: 'Spot terbaik untuk menikmati matahari terbit dengan latar belakang Gunung Bromo, Batok, dan Semeru yang megah.',
    tips: 'Berangkat jam 2 pagi dari Malang. Sewa jeep lokal untuk pengalaman terbaik.',
    coordinates: { lat: -7.9186, lng: 112.9463 },
    ticketPrice: { min: 35000, max: 50000 },
    openHours: '24 Jam (terbaik 04:00 - 07:00)',
  },
  {
    id: '8',
    name: 'Coban Rondo',
    slug: 'coban-rondo',
    category: 'alam',
    location: 'Pujon, Malang',
    distance: '30 km dari Kota',
    crowdLevel: 'medium',
    rating: 4.6,
    reviewCount: 2105,
    image: 'https://asset.kompas.com/crops/DELgpewLf7Dli7oVBR7OzzY7nwk=/0x0:1149x766/1200x800/data/photo/2021/08/25/6126168e3be6b.jpg',
    tags: ['#AirTerjun', '#Legendaris', '#Keluarga'],
    description: 'Air terjun legendaris setinggi 84 meter dengan legenda cinta yang menyentuh hati. Area piknik luas di sekitar air terjun.',
    tips: 'Ada area outbound dan flying fox. Cocok untuk wisata keluarga akhir pekan.',
    coordinates: { lat: -7.8759, lng: 112.4532 },
    ticketPrice: { min: 20000, max: 35000 },
    openHours: '08:00 - 16:00',
  },
  {
    id: '9',
    name: 'Gunung Banyak',
    slug: 'gunung-banyak',
    category: 'alam',
    location: 'Batu, Malang',
    distance: '20 km dari Kota',
    crowdLevel: 'low',
    rating: 4.5,
    reviewCount: 678,
    image: 'https://statik.tempo.co/data/2018/12/15/id_804296/804296_720.jpg',
    tags: ['#Paralayang', '#Adventure', '#ViewKota'],
    description: 'Spot paralayang terbaik di Jawa Timur dengan pemandangan kota Batu dari ketinggian. Tersedia tandem flight untuk pemula.',
    tips: 'Harga tandem flight mulai 350rb/orang. Terbang terbaik jam 10-14 saat angin stabil.',
    coordinates: { lat: -7.8612, lng: 112.5101 },
    ticketPrice: { min: 10000, max: 350000 },
    openHours: '08:00 - 16:00',
  },
  {
    id: '10',
    name: 'Kebun Teh Wonosari',
    slug: 'kebun-teh-wonosari',
    category: 'alam',
    location: 'Lawang, Malang',
    distance: '25 km dari Kota',
    crowdLevel: 'low',
    rating: 4.4,
    reviewCount: 1230,
    image: 'https://pict.sindonews.com/dyn/850/pena/news/2020/09/04/704/153986/kebun-teh-wonosari-jadi-the-most-valuable-seller-di-ajang-kemenparekraf-fec.png',
    tags: ['#KebunTeh', '#Hijau', '#Relaksasi'],
    description: 'Hamparan perkebunan teh hijau seluas 1.144 hektar dengan udara sejuk pegunungan. Ada pabrik teh yang bisa dikunjungi.',
    tips: 'Datang pagi untuk kabut yang estetik. Beli teh langsung dari pabrik, harga lebih murah.',
    coordinates: { lat: -7.8345, lng: 112.6789 },
    ticketPrice: { min: 15000, max: 25000 },
    openHours: '07:00 - 17:00',
  },
  {
    id: '11',
    name: 'Air Terjun Coban Sewu',
    slug: 'coban-sewu',
    category: 'alam',
    location: 'Pronojiwo, Lumajang',
    distance: '90 km dari Kota',
    crowdLevel: 'low',
    rating: 4.8,
    reviewCount: 445,
    image: 'https://images.unsplash.com/photo-1494472155656-f34e81b17ddc?w=800&auto=format',
    tags: ['#AirTerjun', '#Terlebar', '#Hidden'],
    description: 'Air terjun terlebar di Jawa Timur dengan tirai air yang membentang sepanjang 100 meter. Pemandangan luar biasa spektakuler.',
    tips: 'Perjalanan cukup jauh, siapkan fisik dan perbekalan. Trek menurun cukup curam, pakai sepatu gunung.',
    coordinates: { lat: -8.1523, lng: 112.9876 },
    ticketPrice: { min: 10000, max: 15000 },
    openHours: '07:00 - 15:00',
  },
  {
    id: '12',
    name: 'Hutan Pinus Semeru',
    slug: 'hutan-pinus-semeru',
    category: 'alam',
    location: 'Tumpang, Malang',
    distance: '40 km dari Kota',
    crowdLevel: 'low',
    rating: 4.3,
    reviewCount: 312,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIClnWgyBH4my6QZ3pXZmp8OZZ1Ljnq6a5Gd1aqzXQZnzM1eBvcwQ7OPo&s=10',
    tags: ['#HutanPinus', '#Camping', '#Instagramable'],
    description: 'Hutan pinus yang teduh dan asri di lereng Gunung Semeru. Spot camping populer dengan suasana tenang dan udara segar.',
    tips: 'Bawa jaket tebal, suhu malam bisa turun sampai 10°C. Ada area camping berbayar.',
    coordinates: { lat: -8.0456, lng: 112.8543 },
    ticketPrice: { min: 5000, max: 10000 },
    openHours: '24 Jam',
  },
  {
    id: '13',
    name: 'Bukit Teletubbies',
    slug: 'bukit-teletubbies',
    category: 'alam',
    location: 'Ngadas, Malang',
    distance: '60 km dari Kota',
    crowdLevel: 'low',
    rating: 4.6,
    reviewCount: 567,
    image: 'https://awsimages.detik.net.id/community/media/visual/2022/01/04/nikmati-hijaunya-padang-savana-dan-bukit-teletubbies-di-bromo-1_169.jpeg?w=1200',
    tags: ['#PadangRumput', '#Unik', '#Bromo'],
    description: 'Padang rumput hijau berbukit-bukit yang menyerupai latar serial Teletubbies. Terletak di jalur menuju Bromo via Tumpang.',
    tips: 'Paling hijau saat musim hujan (Nov-Mar). Bagus untuk foto saat pagi hari.',
    coordinates: { lat: -7.9654, lng: 112.9123 },
    ticketPrice: { min: 5000, max: 10000 },
    openHours: '06:00 - 17:00',
  },
  {
    id: '14',
    name: 'Pemandian Cangar',
    slug: 'pemandian-cangar',
    category: 'alam',
    location: 'Batu, Malang',
    distance: '28 km dari Kota',
    crowdLevel: 'medium',
    rating: 4.3,
    reviewCount: 1890,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcToa4nJLclDk7PR87uOUZ79cXNBf-Gl-fzJ16P_Xjv4SqjgOA2YzdJcuNHU&s=10',
    tags: ['#AirPanas', '#Alami', '#Relaksasi'],
    description: 'Sumber air panas alami di tengah hutan pinus dengan suhu air 40-50°C. Kolam-kolam alami dikelilingi pepohonan rindang.',
    tips: 'Datang weekday untuk menghindari keramaian. Bawa handuk dan baju ganti sendiri.',
    coordinates: { lat: -7.7856, lng: 112.5234 },
    ticketPrice: { min: 15000, max: 25000 },
    openHours: '07:00 - 16:00',
  },
  // ═══════════════════════════════════════════
  // PANTAI (5 destinations)
  // ═══════════════════════════════════════════
  {
    id: '3',
    name: 'Pantai Licin',
    slug: 'pantai-licin',
    category: 'pantai',
    location: 'Sumbermanjing Wetan',
    distance: '65 km dari Kota',
    crowdLevel: 'low',
    rating: 4.9,
    reviewCount: 67,
    image: 'https://upload.wikimedia.org/wikipedia/id/9/99/Pantai_Licin_Malang.jpg',
    tags: ['#PasirHitam', '#Terpencil', '#Surfing'],
    description: 'Pasir hitam legam yang kontras dengan buih laut putih. Surga tersembunyi para petualang sejati.',
    tips: 'Bawa kendaraan 4WD atau motor trail. Jalan menuju ke sana masih belum diaspal.',
    coordinates: { lat: -8.4512, lng: 112.7234 },
    ticketPrice: { min: 5000, max: 10000 },
    openHours: '24 Jam',
  },
  {
    id: '15',
    name: 'Pantai Tiga Warna',
    slug: 'pantai-tiga-warna',
    category: 'pantai',
    location: 'Malang Selatan',
    distance: '70 km dari Kota',
    crowdLevel: 'low',
    rating: 4.8,
    reviewCount: 876,
    image: 'https://cozzy.id/uploads/0000/630/2024/09/25/penginapan-murah-malang-hotel-murah-cozzyid.jpg',
    tags: ['#TigaWarna', '#Snorkeling', '#Konservasi'],
    description: 'Pantai dengan gradasi 3 warna air yang unik — biru tua, biru muda, dan hijau tosca. Area konservasi dengan akses terbatas.',
    tips: 'WAJIB reservasi dulu karena kuota dibatasi 100 orang/hari. Bawa perlengkapan snorkeling sendiri.',
    coordinates: { lat: -8.4321, lng: 112.6789 },
    ticketPrice: { min: 25000, max: 35000 },
    openHours: '07:00 - 15:00 (kuota terbatas)',
  },
  {
    id: '16',
    name: 'Pantai Balekambang',
    slug: 'pantai-balekambang',
    category: 'pantai',
    location: 'Gondanglegi, Malang',
    distance: '55 km dari Kota',
    crowdLevel: 'medium',
    rating: 4.5,
    reviewCount: 2345,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJBvxoKjUIMTRo6Hui0wJLjk-lVC1xAj9jbKnf67qw16WIPtty8EPWsnxQ&s=10',
    tags: ['#Pura', '#BatuKarang', '#Ikonik'],
    description: 'Pantai ikonik Malang dengan pura Hindu di atas batu karang yang dihubungkan jembatan. Sering disebut Tanah Lot-nya Jawa Timur.',
    tips: 'Datang saat air surut untuk berjalan ke pura. Sunset di sini sangat memukau.',
    coordinates: { lat: -8.3967, lng: 112.5678 },
    ticketPrice: { min: 15000, max: 20000 },
    openHours: '06:00 - 18:00',
  },
  {
    id: '17',
    name: 'Pantai Sendang Biru',
    slug: 'pantai-sendang-biru',
    category: 'pantai',
    location: 'Sumbermanjing, Malang',
    distance: '68 km dari Kota',
    crowdLevel: 'medium',
    rating: 4.4,
    reviewCount: 1234,
    image: 'https://asset.kompas.com/crops/LyqJOF381IFBFl1afbNWcUzUfGM=/12x13:991x666/1200x800/data/photo/2022/04/21/62612ae77be02.jpg',
    tags: ['#Nelayan', '#Snorkeling', '#SeafoodSegar'],
    description: 'Pelabuhan nelayan tradisional dengan air jernih untuk snorkeling. Gateway ke Pulau Sempu yang terkenal.',
    tips: 'Coba seafood segar langsung dari nelayan. Harga ikan sangat murah dibanding kota.',
    coordinates: { lat: -8.4234, lng: 112.6543 },
    ticketPrice: { min: 10000, max: 15000 },
    openHours: '24 Jam',
  },
  {
    id: '18',
    name: 'Pantai Goa Cina',
    slug: 'pantai-goa-cina',
    category: 'pantai',
    location: 'Sumbermanjing, Malang',
    distance: '72 km dari Kota',
    crowdLevel: 'low',
    rating: 4.7,
    reviewCount: 456,
    image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/14/fe/20/d6/goa-cina-beach.jpg?w=1200&h=-1&s=1',
    tags: ['#GoaKarang', '#Eksotis', '#Hidden'],
    description: 'Pantai karang eksotis dengan goa alami yang terbentuk dari erosi laut. Formasi batu karang yang dramatis dan air laut jernih.',
    tips: 'Hati-hati saat masuk goa saat ombak besar. Bawa alas kaki anti-selip.',
    coordinates: { lat: -8.4567, lng: 112.7456 },
    ticketPrice: { min: 10000, max: 15000 },
    openHours: '06:00 - 17:00',
  },
  // ═══════════════════════════════════════════
  // BUDAYA & SEJARAH (5 destinations)
  // ═══════════════════════════════════════════
  {
    id: '5',
    name: 'Candi Singosari',
    slug: 'candi-singosari',
    category: 'budaya',
    location: 'Singosari, Malang',
    distance: '10 km dari Kota',
    crowdLevel: 'low',
    rating: 4.5,
    reviewCount: 456,
    image: 'https://upload.wikimedia.org/wikipedia/commons/1/15/Candi_Singosari_B.JPG',
    tags: ['#Sejarah', '#SpiritualTrail', '#KerajaanKuno'],
    description: 'Peninggalan megah Kerajaan Singosari abad ke-13. Nilai sejarah yang luar biasa di pinggir kota.',
    tips: 'Kunjungi saat senja hari untuk pencahayaan foto terbaik.',
    coordinates: { lat: -7.9087, lng: 112.6659 },
    ticketPrice: { min: 5000, max: 5000 },
    openHours: '07:00 - 17:00',
  },
  {
    id: '19',
    name: 'Museum Angkut',
    slug: 'museum-angkut',
    category: 'budaya',
    location: 'Batu, Malang',
    distance: '22 km dari Kota',
    crowdLevel: 'high',
    rating: 4.6,
    reviewCount: 5432,
    image: 'https://cdn-jpr.jawapos.com/images/32/2025/12/03/4e6aaecb-745c-45c5-8e48-f7263ca014b0-2609799398.jpeg',
    tags: ['#Museum', '#Transportasi', '#Keluarga'],
    description: 'Museum transportasi terbesar di Asia Tenggara dengan koleksi ratusan kendaraan dari berbagai era dan negara.',
    tips: 'Butuh 3-4 jam untuk keliling semua zona. Beli tiket online lebih murah Rp 10.000.',
    coordinates: { lat: -7.8876, lng: 112.5234 },
    ticketPrice: { min: 70000, max: 100000 },
    openHours: '12:00 - 20:00',
  },
  {
    id: '20',
    name: 'Jatim Park 3',
    slug: 'jatim-park-3',
    category: 'budaya',
    location: 'Batu, Malang',
    distance: '22 km dari Kota',
    crowdLevel: 'high',
    rating: 4.5,
    reviewCount: 3456,
    image: 'https://nagantour.com/wp-content/uploads/2023/12/jatim-park-3-1.webp',
    tags: ['#TamanRekreasi', '#Edukasi', '#Dinosaurus'],
    description: 'Taman rekreasi edukasi dengan tema dinosaurus dan sains. Ada Dino Park, museum tubuh manusia, dan area bermain interaktif.',
    tips: 'Beli tiket terusan Jatim Park 1+2+3 lebih hemat. Weekend sangat ramai, datang weekday.',
    coordinates: { lat: -7.8923, lng: 112.5267 },
    ticketPrice: { min: 75000, max: 120000 },
    openHours: '10:00 - 17:00',
  },
  {
    id: '21',
    name: 'Kampung Warna-Warni Jodipan',
    slug: 'kampung-warna-warni-jodipan',
    category: 'budaya',
    location: 'Malang Kota',
    distance: '2 km dari Pusat',
    crowdLevel: 'medium',
    rating: 4.3,
    reviewCount: 3210,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrKeZQGqWGotUYIMcNZ1lYJPt8o1wfhuvPjckBdParJPFyPMNEFFEzSKQ&s=10',
    tags: ['#Instagramable', '#WarnWarni', '#KotaTua'],
    description: 'Kampung warna-warni yang instagramable di tepi Sungai Brantas. Dulunya kampung kumuh, kini jadi ikon wisata Malang.',
    tips: 'Pagi hari cahayanya paling bagus untuk foto. Ada jembatan kaca untuk view terbaik.',
    coordinates: { lat: -7.9834, lng: 112.6345 },
    ticketPrice: { min: 3000, max: 5000 },
    openHours: '06:00 - 18:00',
  },
  {
    id: '22',
    name: 'Alun-Alun Batu',
    slug: 'alun-alun-batu',
    category: 'budaya',
    location: 'Batu, Malang',
    distance: '20 km dari Kota',
    crowdLevel: 'medium',
    rating: 4.4,
    reviewCount: 4567,
    image: 'https://cdn2.gnfi.net/gnfi/uploads/articles/large-menjelajahi-alun-alun-kota-wisata-batu-zoNVwcnFU8.jpg',
    tags: ['#BintangRaksasa', '#Malam', '#PusatKota'],
    description: 'Pusat kota Batu dengan landmark bintang raksasa yang ikonik. Area terbuka dengan berbagai wahana dan kuliner malam.',
    tips: 'Paling ramai dan seru malam hari. Ada pasar malam dengan jajanan khas Batu.',
    coordinates: { lat: -7.8767, lng: 112.5278 },
    ticketPrice: { min: 0, max: 0 },
    openHours: '24 Jam',
  },
  // ═══════════════════════════════════════════
  // KULINER (6 destinations)
  // ═══════════════════════════════════════════
  {
    id: '6',
    name: 'Warung Kopi Pak Ndut',
    slug: 'warung-kopi-pak-ndut',
    category: 'kuliner',
    location: 'Jl. Ijen, Malang Kota',
    distance: '3 km dari Pusat',
    crowdLevel: 'medium',
    rating: 4.9,
    reviewCount: 1203,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBHCiOtiuJPWDHUUSoF2HSeSr4ura60obud3aWMZnKqEkDix1cOFk-DlnSlDCtF-oYC3gHhZ5PRsPnimg9eqryOmB0C8OhnaGa7ELCc55jjyiMpuBWlsWmos8amAEa66uInZAgh_ISgE42vaTyyBNZN1heUelvmiKjbnd9nnWf0Xa7uExU-FXkXQcXxHy6Kc0Z05gZ8as6MQPgu5Xgigce8X7yku7_DWlvD-S_dIct-wlAtC1e1vHe2sycPeCUYRFb9Xp6pP4wHlA',
    tags: ['#KopiLokal', '#UMKM', '#IconikMalang'],
    description: 'Warung kopi legendaris yang sudah 40 tahun melayani warga Malang. Kopi robusta lokal dengan citarasa unik.',
    tips: 'Coba kopi item panas dengan pisang goreng. Buka dari jam 6 pagi.',
    coordinates: { lat: -7.9666, lng: 112.6209 },
    foodPrice: { min: 5000, max: 25000 },
    openHours: '06:00 - 22:00',
  },
  {
    id: '23',
    name: 'Warung Bakso President',
    slug: 'warung-bakso-president',
    category: 'kuliner',
    location: 'Jl. Batanghari, Malang',
    distance: '3 km dari Pusat',
    crowdLevel: 'high',
    rating: 4.7,
    reviewCount: 3456,
    image: 'https://images.unsplash.com/photo-1555126634-323283e090fa?w=800&auto=format',
    tags: ['#Bakso', '#Legendaris', '#WajibCoba'],
    description: 'Bakso legendaris Malang yang sudah berdiri sejak 1970-an. Bakso urat jumbo dan kuah kaldu sapi yang kaya rasa.',
    tips: 'Datang sebelum jam 12 siang, sering habis sebelum sore. Coba bakso urat spesial.',
    coordinates: { lat: -7.9745, lng: 112.6312 },
    foodPrice: { min: 15000, max: 35000 },
    openHours: '08:00 - 15:00 (habis = tutup)',
  },
  {
    id: '24',
    name: 'Rawon Nguling',
    slug: 'rawon-nguling',
    category: 'kuliner',
    location: 'Nguling, Pasuruan',
    distance: '50 km dari Kota',
    crowdLevel: 'medium',
    rating: 4.8,
    reviewCount: 2100,
    image: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=800&auto=format',
    tags: ['#Rawon', '#Authentic', '#JawaTimur'],
    description: 'Rawon paling authentic dengan kuah hitam pekat dari kluwek asli. Daging empuk dan bumbu rempah yang kuat.',
    tips: 'Pesan rawon dengan telur asin dan sambal terasi. Buka pagi, sering antri panjang.',
    coordinates: { lat: -7.7234, lng: 112.8765 },
    foodPrice: { min: 20000, max: 40000 },
    openHours: '06:00 - 14:00',
  },
  {
    id: '25',
    name: 'Nasi Pecel Bu Tinuk',
    slug: 'nasi-pecel-bu-tinuk',
    category: 'kuliner',
    location: 'Jl. Semeru, Malang',
    distance: '2 km dari Pusat',
    crowdLevel: 'medium',
    rating: 4.6,
    reviewCount: 1876,
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&auto=format',
    tags: ['#NasiPecel', '#KhasMalang', '#Sarapan'],
    description: 'Nasi pecel khas Malang dengan bumbu kacang yang gurih manis. Lauk lengkap dari tempe mendoan sampai ayam goreng.',
    tips: 'Menu terlaris: nasi pecel komplit + es jeruk. Datang pagi untuk pilihan lauk lengkap.',
    coordinates: { lat: -7.9712, lng: 112.6245 },
    foodPrice: { min: 10000, max: 25000 },
    openHours: '06:00 - 13:00',
  },
  {
    id: '26',
    name: 'Depot Es Krim Sumber Hidup',
    slug: 'depot-es-krim-sumber-hidup',
    category: 'kuliner',
    location: 'Batu, Malang',
    distance: '22 km dari Kota',
    crowdLevel: 'medium',
    rating: 4.5,
    reviewCount: 987,
    image: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=800&auto=format',
    tags: ['#EsKrim', '#Artisanal', '#Sejak1960'],
    description: 'Es krim artisanal legendaris sejak 1960-an. Dibuat dari susu sapi segar lokal Batu dengan rasa yang creamy dan natural.',
    tips: 'Coba rasa alpukat dan durian, signature mereka. Ada paket es krim 3 rasa.',
    coordinates: { lat: -7.8834, lng: 112.5289 },
    foodPrice: { min: 8000, max: 25000 },
    openHours: '09:00 - 21:00',
  },
  {
    id: '27',
    name: 'Rumah Makan Inggil',
    slug: 'rumah-makan-inggil',
    category: 'kuliner',
    location: 'Malang Kota',
    distance: '1 km dari Pusat',
    crowdLevel: 'medium',
    rating: 4.7,
    reviewCount: 2345,
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format',
    tags: ['#Kolonial', '#Heritage', '#FineDining'],
    description: 'Restoran bersejarah di gedung kolonial Belanda tahun 1930-an. Menu masakan Jawa klasik dengan presentasi modern.',
    tips: 'Reservasi dulu untuk weekend. Coba menu rijsttafel untuk pengalaman lengkap.',
    coordinates: { lat: -7.9778, lng: 112.6334 },
    foodPrice: { min: 35000, max: 150000 },
    openHours: '10:00 - 22:00',
  },
  // ═══════════════════════════════════════════
  // DESA WISATA (1 destination)
  // ═══════════════════════════════════════════
  {
    id: '4',
    name: 'Desa Wisata Gubugklakah',
    slug: 'gubugklakah',
    category: 'desa',
    location: 'Poncokusumo, Malang',
    distance: '30 km dari Kota',
    crowdLevel: 'low',
    rating: 4.6,
    reviewCount: 312,
    image: 'https://blue.kumparan.com/image/upload/fl_progressive,fl_lossy,c_fill,f_auto,q_auto:best,w_640/v1634025439/01h94yafcfq55x3e9e7ye8w2fq.jpg',
    tags: ['#KulturLokal', '#Homestay', '#Pertanian'],
    description: 'Desa wisata agraris dengan view Semeru yang memukau. Nikmati hidup sebagai petani sehari penuh.',
    tips: 'Pesan homestay minimal H-3. Tersedia paket petik apel langsung dari kebun.',
    coordinates: { lat: -8.0124, lng: 112.8876 },
    ticketPrice: { min: 25000, max: 100000 },
    openHours: '08:00 - 17:00',
  },
  // ═══════════════════════════════════════════
  // ALAM + ADVENTURE EXTRA
  // ═══════════════════════════════════════════
  {
    id: '28',
    name: 'Blue Lagoon Tirta Nirmala',
    slug: 'blue-lagoon-tirta-nirmala',
    category: 'alam',
    location: 'Batu, Malang',
    distance: '25 km dari Kota',
    crowdLevel: 'low',
    rating: 4.5,
    reviewCount: 345,
    image: 'https://zjglidcehtsqqqhbdxyp.supabase.co/storage/v1/object/public/atourin/images/destination/sleman/blue-lagoon-profile1697021544.jpeg?x-image-process=image/resize,p_100,limit_1/imageslim',
    tags: ['#KolamAlami', '#BiruJernih', '#Tersembunyi'],
    description: 'Kolam alami dengan air biru jernih yang mengagumkan. Dikelilingi tebing batu dan vegetasi tropis yang rimbun.',
    tips: 'Bawa perlengkapan renang sendiri. Air cukup dingin, cocok untuk siang hari.',
    coordinates: { lat: -7.8678, lng: 112.5456 },
    ticketPrice: { min: 15000, max: 25000 },
    openHours: '08:00 - 16:00',
  },
  {
    id: '29',
    name: 'Coban Talun',
    slug: 'coban-talun',
    category: 'alam',
    location: 'Batu, Malang',
    distance: '23 km dari Kota',
    crowdLevel: 'medium',
    rating: 4.4,
    reviewCount: 1567,
    image: 'https://www.paketwisatabromo.co.id/wp-content/uploads/2022/07/@alhi_dzirin.webp',
    tags: ['#AirTerjun', '#Camping', '#TamanHutan'],
    description: 'Air terjun setinggi 75 meter dengan area camping yang luas. Ada Rainbow Waterfall dan taman hutan raya yang asri.',
    tips: 'Sewa tenda di lokasi jika tidak bawa sendiri. Tersedia warung makan lokal.',
    coordinates: { lat: -7.8234, lng: 112.4987 },
    ticketPrice: { min: 25000, max: 40000 },
    openHours: '07:00 - 16:00',
  },
]

export const posts: Post[] = [
  {
    id: '1',
    author: 'Sam_Ganteng',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDWtoxROcMHgUeoZf2sW7SCevSVcFVIRxCpponRQK-7acvqsN-U9B_JEDQrmB7DC1In6e3ML7FfN7EC0M2PIjYWVyH0Sr2eka0rW0opT0edC9vQqAdSgBjwb_hlFVYl0R2Dg4lSiYCym77gIACBF4OoADjKbj1nWfH8WU5GoJys4c6brq7H-9uAKRweUP4TPzxNMBIq00MoelCkMsyrwu0qdRG9cFH416w0o0H1XQ5mjQTeQ76zrCtjg7RvKoABdLfum0IjgtmrLA',
    badge: 'Local Expert',
    time: '2 jam lalu',
    category: 'Tips Lokal',
    title: 'Jalur ke Bromo saat ini cerah, keramaian rendah!',
    body: 'Baru saja turun dari Penanjakan 1. Cuaca sangat mendukung, tidak ada kabut tebal. Untuk yang mau naik sekarang, jalannya lancar jaya tapi tetep waspaya pasir licin ya Sam!',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBh4kt9kSgB7jg5ItFY8B9GbxIiWr2yI9mRzpzrdsSZcrOKP_xpv03_6yEA9RmLqC5F47G0-zPmOEcffIGVMFly0OOQfUSzDtsR022OL9KUzao8ui3-UaSdETC25wH7h1_H5hD9Y3hcY9SFVcOD6nSwS2JHM0YK9jqxyR93ak2liDxiT5CLSzOumXaA3EMOc6BqLccV_TBFKOgN7RauocSXYDx2ZfmrhQu-BTdJhHFiVjSVpUCaxT37rzf-Nvfl82lmqq5vckVGww',
    votes: 1247,
    comments: 89,
    tags: ['bromo', 'cuaca', 'tips'],
  },
  {
    id: '2',
    author: 'Dewi_Malang',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDWtoxROcMHgUeoZf2sW7SCevSVcFVIRxCpponRQK-7acvqsN-U9B_JEDQrmB7DC1In6e3ML7FfN7EC0M2PIjYWVyH0Sr2eka0rW0opT0edC9vQqAdSgBjwb_hlFVYl0R2Dg4lSiYCym77gIACBF4OoADjKbj1nWfH8WU5GoJys4c6brq7H-9uAKRweUP4TPzxNMBIq00MoelCkMsyrwu0qdRG9cFH416w0o0H1XQ5mjQTeQ76zrCtjg7RvKoABdLfum0IjgtmrLA',
    badge: 'Foodie',
    time: '5 jam lalu',
    category: 'Kuliner',
    title: 'Nemu hidden gem kuliner di Pecinan! Wajib dikunjungi',
    body: 'Warung Es Krim Toko Oen Malang masih tetap legend sampe sekarang. Coba es krim vanila sambil nikmatin interior kolonial yang masih orisinal dari 1930-an.',
    votes: 823,
    comments: 47,
    tags: ['kuliner', 'pecinan', 'sejarah'],
  },
  {
    id: '3',
    author: 'TrekkingBro',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDWtoxROcMHgUeoZf2sW7SCevSVcFVIRxCpponRQK-7acvqsN-U9B_JEDQrmB7DC1In6e3ML7FfN7EC0M2PIjYWVyH0Sr2eka0rW0opT0edC9vQqAdSgBjwb_hlFVYl0R2Dg4lSiYCym77gIACBF4OoADjKbj1nWfH8WU5GoJys4c6brq7H-9uAKRweUP4TPzxNMBIq00MoelCkMsyrwu0qdRG9cFH416w0o0H1XQ5mjQTeQ76zrCtjg7RvKoABdLfum0IjgtmrLA',
    badge: 'Adventurer',
    time: '1 hari lalu',
    category: 'Petualangan',
    title: 'Review jujur: Trekking Coban Pelangi Atas 5 jam',
    body: 'Perjalanan 5 jam yang benar-benar worth it! Pemandangan di puncak benar-benar tidak ada tandingannya. Bawa air minimal 2 liter dan snack banyak.',
    votes: 654,
    comments: 112,
    tags: ['trekking', 'coban-pelangi', 'review'],
  },
]

export const crowdReports: CrowdReport[] = [
  { name: 'Bromo', level: 'rendah', color: '#1FAF8F', trend: 'down' },
  { name: 'Jatim Park 3', level: 'padat', color: '#EF4444', trend: 'up' },
  { name: 'Kampung Warna', level: 'sedang', color: '#EAB308', trend: 'stable' },
  { name: 'BNS', level: 'lancar', color: '#1FAF8F', trend: 'down' },
  { name: 'Coban Pelangi', level: 'sedang', color: '#EAB308', trend: 'up' },
  { name: 'Selecta', level: 'padat', color: '#EF4444', trend: 'up' },
]
